### ISSUE TITLE
weakauras

### ISSUE THREAD

**Issue by gamer4eg** [laytya/Vanilla-Addons#1]
А слабо викауру бэкпортнуть?
Алсо если надо принесу бэкпорт на 2.4.3 на посмотреть.

**Comment by gamer4eg** [comment]
Вот бэкпорты кста:
2.4.3 https://github.com/obszczymucha/WeakAuras
3.3.5 https://github.com/Bunny67/WeakAuras-WotLK

**Comment by laytya** [comment]
Я смотрел уже - не реально - там считай все переписывать нада. Слишком серьезно поменяли всю систему евентов и комбат лога.
