### ISSUE TITLE
Вопрос по LazyScript

### ISSUE THREAD

**Issue by gamer4eg** [laytya/Vanilla-Addons#2]
Слушай, если ты вдруг играешь на кастомках вроде V+ или Черепахи...
Добавление кастомных скиллов ломают работу сокращений(вызовов скиллов по сокращению, а не по полному имени)
Как починить? Хотя бы на уровне добавить 2.5 нужных скилла.
А то без сокращений не работает указание цели и проверка кд...
Если что я за Черепаховый сервер спрашиваю.
Ну или это просто паладин такой кривой?
В любом случае мне бы хотя-бы пару скиллов добавить. В идеале мануал. Или там сложно?

**Comment by gamer4eg** [comment]
И да, я уверен ты слышал про lazyScript
Все кто хотя-бы чуть-чуть могут в lua про него слышали, ибо лень-двигатель прогресса, а сила одной кнопки в рейде-абсолютна!

UPD да он у тебя же и есть в репо, я и забыл, лол.

**Comment by laytya** [comment]
Мне нужны данные по скилам. У меня нет чаров чтоб добавить и проверять.
